# Generated by Django 5.2.1 on 2025-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
